 version: "3.8"
 
 services:
   bot:
     build: .
     container_name: vpn_bot
     restart: always
 
     environment:
       - BOT_TOKEN=${BOT_TOKEN}
       - ADMIN_IDS=${ADMIN_IDS}
       - DATABASE_URL=sqlite+aiosqlite:///data/db.sqlite3
       - XUI_URL=${XUI_URL}
       - XUI_USERNAME=${XUI_USERNAME}
       - XUI_PASSWORD=${XUI_PASSWORD}
       - XUI_INBOUND_ID=${XUI_INBOUND_ID:-1}
       - CARD_NUMBER=${CARD_NUMBER}
       - CARD_HOLDER=${CARD_HOLDER}
 
     volumes:
       - ./data:/app/data
